name: blue_green
description: An application which uses service routing using auto generation code
version: 1.0.0
repository: https://github.com/manasa0608/blue_green

environment:
  sdk: ^3.0.3
dependencies:
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10


