name: blue_green_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  path: ^1.7.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  postgres: ^3.0.5
  shelf_router:
  riverpod:
  memory_cache: ^1.2.0

dev_dependencies:
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  annotations:
    path: ../annotations
  generators:
    path: ../generators
  build_runner:

flutter:
  uses-material-design: true
