name: annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/manasa0608/blue_green

environment:
  sdk: ^3.0.3

dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
