targets:
  $default:
    builders:
      generators|annotations:
        enabled: true
        generate_for:
          - lib/*.dart
builders:
  greenGeneratorBuilder:
    import: 'package:generators/generators.dart'
    builder_factories: [ 'greenGeneratorBuilder' ]
    auto_apply: dependents
    build_extensions: { ".dart": [ ".g.part" ] }
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
