name: generators
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.3
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:
  annotations:
    path: ../annotations

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: